
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.Statement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import net.proteanit.sql.DbUtils;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Kryzle Rahne
 */
public class booking extends javax.swing.JFrame {
public int flag = 0;

    /**
     * Creates new form booking
     */
    public booking() {
        initComponents();
        setLocationRelativeTo(null);
        dontExist.setVisible(false);
        lblFee.setVisible(false);
        jTextField_fee.setVisible(false);
        lblStatus.setVisible(false);
        jTextField_status.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        paymentOptions = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        lblName = new javax.swing.JLabel();
        jTextField_name = new javax.swing.JTextField();
        searchButton = new javax.swing.JButton();
        dontExist = new javax.swing.JLabel();
        lblDoctor = new javax.swing.JLabel();
        jComboBox_doctor = new javax.swing.JComboBox<>();
        lblDate = new javax.swing.JLabel();
        lblTime = new javax.swing.JLabel();
        jComboBox_time = new javax.swing.JComboBox<>();
        lblPayment = new javax.swing.JLabel();
        lblFee = new javax.swing.JLabel();
        bookButton = new javax.swing.JButton();
        cancelButton = new javax.swing.JButton();
        jTextField_fee = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        tableRecord = new javax.swing.JTable();
        jTextField_date = new javax.swing.JTextField();
        lblStatus = new javax.swing.JLabel();
        jTextField_status = new javax.swing.JTextField();
        jCheckBox_cash = new javax.swing.JCheckBox();
        jCheckBox_card = new javax.swing.JCheckBox();
        jLabel3 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Booking Appointment");
        setPreferredSize(new java.awt.Dimension(795, 490));

        jPanel1.setBackground(new java.awt.Color(236, 235, 235));

        jLabel1.setFont(new java.awt.Font("Bubbleboddy Neue Trial", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(105, 191, 175));
        jLabel1.setText("BOOK AN APPOINTMENT");

        lblName.setFont(new java.awt.Font("Bubbleboddy Neue Trial", 0, 15)); // NOI18N
        lblName.setForeground(new java.awt.Color(102, 102, 102));
        lblName.setText("Patient's Name");

        searchButton.setFont(new java.awt.Font("Bubbleboddy Neue Trial", 0, 14)); // NOI18N
        searchButton.setForeground(new java.awt.Color(102, 102, 102));
        searchButton.setText("Search");
        searchButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchButtonActionPerformed(evt);
            }
        });

        dontExist.setFont(new java.awt.Font("Bubbleboddy Neue Trial", 0, 18)); // NOI18N
        dontExist.setForeground(new java.awt.Color(255, 51, 51));
        dontExist.setText("Name Does Not Exist!");

        lblDoctor.setFont(new java.awt.Font("Bubbleboddy Neue Trial", 0, 15)); // NOI18N
        lblDoctor.setForeground(new java.awt.Color(102, 102, 102));
        lblDoctor.setText("Choose Doctor:");

        jComboBox_doctor.setFont(new java.awt.Font("Affogato Light", 0, 13)); // NOI18N
        jComboBox_doctor.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select", "Dr. Sanchez (General Practitioners)", "Dr. Atienza (Cardiologist)", "Dr. Palbacal (Opthalmologist)", "Dra. Manalo (Allergy & Immunologist)", "Dr. Castillo (Neurologist)", "Dr. Cueto (Urologist)", "Dr. Agena (Obstetrician)", "Dr. Abarintos (Pediatrician)", " " }));

        lblDate.setFont(new java.awt.Font("Bubbleboddy Neue Trial", 0, 15)); // NOI18N
        lblDate.setForeground(new java.awt.Color(102, 102, 102));
        lblDate.setText("Choose Date");

        lblTime.setFont(new java.awt.Font("Bubbleboddy Neue Trial", 0, 15)); // NOI18N
        lblTime.setForeground(new java.awt.Color(102, 102, 102));
        lblTime.setText("Choose Time");

        jComboBox_time.setFont(new java.awt.Font("Affogato Light", 0, 13)); // NOI18N
        jComboBox_time.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select", "7:00-8:00 AM", "8:00-9:00 AM", "9:00-10:00 AM", "10:00 - 11:00 AM", "11:00- 12:00 PM" }));

        lblPayment.setFont(new java.awt.Font("Bubbleboddy Neue Trial", 0, 15)); // NOI18N
        lblPayment.setForeground(new java.awt.Color(102, 102, 102));
        lblPayment.setText("Payment Option");

        lblFee.setFont(new java.awt.Font("Bubbleboddy Neue Trial", 0, 15)); // NOI18N
        lblFee.setForeground(new java.awt.Color(102, 102, 102));
        lblFee.setText("Appointment Fee:");

        bookButton.setFont(new java.awt.Font("Bubbleboddy Neue Trial", 0, 16)); // NOI18N
        bookButton.setForeground(new java.awt.Color(102, 102, 102));
        bookButton.setText("Book");
        bookButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bookButtonActionPerformed(evt);
            }
        });

        cancelButton.setFont(new java.awt.Font("Bubbleboddy Neue Trial", 0, 16)); // NOI18N
        cancelButton.setForeground(new java.awt.Color(102, 102, 102));
        cancelButton.setText("Cancel");
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });

        jTextField_fee.setFont(new java.awt.Font("Affogato Light", 0, 14)); // NOI18N
        jTextField_fee.setText("P1,000.00");
        jTextField_fee.setEnabled(false);

        tableRecord.setFont(new java.awt.Font("Affogato Light", 0, 14)); // NOI18N
        tableRecord.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Patient ID", "Name", "Address", "Birthday", "Age", "Gender", "Phone Number", "Date", "Illness", "BloodType"
            }
        ));
        jScrollPane2.setViewportView(tableRecord);

        jTextField_date.setFont(new java.awt.Font("Affogato Light", 0, 13)); // NOI18N

        lblStatus.setFont(new java.awt.Font("Bubbleboddy Neue Trial", 0, 15)); // NOI18N
        lblStatus.setForeground(new java.awt.Color(102, 102, 102));
        lblStatus.setText("Status:");

        jTextField_status.setFont(new java.awt.Font("Affogato Light", 0, 14)); // NOI18N
        jTextField_status.setText("Pending");
        jTextField_status.setEnabled(false);

        paymentOptions.add(jCheckBox_cash);
        jCheckBox_cash.setFont(new java.awt.Font("Affogato Light", 0, 13)); // NOI18N
        jCheckBox_cash.setText("Cash Walk-in Payment");
        jCheckBox_cash.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jCheckBox_cashMouseClicked(evt);
            }
        });

        paymentOptions.add(jCheckBox_card);
        jCheckBox_card.setFont(new java.awt.Font("Affogato Light", 0, 13)); // NOI18N
        jCheckBox_card.setText("Card Payment");
        jCheckBox_card.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jCheckBox_cardMouseClicked(evt);
            }
        });

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/book.png"))); // NOI18N

        jLabel11.setFont(new java.awt.Font("Affogato Light", 2, 12)); // NOI18N
        jLabel11.setText("Select your desired schedule for advanced booking medical consultation.");

        jPanel3.setBackground(new java.awt.Color(106, 192, 176));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 374, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 8, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 696, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lblDate)
                                .addGap(28, 28, 28)
                                .addComponent(jTextField_date, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lblDoctor)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jComboBox_doctor, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(41, 41, 41)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblTime)
                            .addComponent(lblPayment))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jCheckBox_cash)
                            .addComponent(jComboBox_time, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jCheckBox_card, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(50, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(155, 155, 155)
                        .addComponent(jLabel3)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel11)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(lblName)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(jTextField_name, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(searchButton))
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                                .addComponent(dontExist)
                                                .addGap(67, 67, 67))))))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(259, 259, 259)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lblStatus)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTextField_status, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lblFee)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTextField_fee, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(bookButton, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(cancelButton, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(35, 35, 35)
                                .addComponent(jLabel11))
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblName)
                    .addComponent(jTextField_name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(searchButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(dontExist)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblDoctor)
                            .addComponent(jComboBox_doctor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(6, 6, 6)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblDate)
                            .addComponent(jTextField_date, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblTime)
                            .addComponent(jComboBox_time, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(6, 6, 6)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblPayment)
                            .addComponent(jCheckBox_cash))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jCheckBox_card)))
                .addGap(6, 6, 6)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblFee)
                    .addComponent(jTextField_fee, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblStatus)
                    .addComponent(jTextField_status, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bookButton)
                    .addComponent(cancelButton))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
        patientMenu pm =new patientMenu();
        pm.setVisible(true);
        dispose();
    }//GEN-LAST:event_cancelButtonActionPerformed

    private void searchButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchButtonActionPerformed
        // TODO add your handling code here:
        String patientName = jTextField_name.getText();
        
        try{
            Class.forName("com.mysql.jdbc.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost/login_register", "root", "");
            Statement st = con.createStatement();
            ResultSet rs = st.executeQuery("select * from patient where name='"+patientName+"'");
           tableRecord.setModel(DbUtils.resultSetToTableModel(rs));
           tableRecord.setAutoResizeMode(tableRecord.AUTO_RESIZE_OFF);
            if (!rs.first()){
                dontExist.setVisible(true);
                jTextField_name.setText(null);
            }
            else
            {
                dontExist.setVisible(false);
                jTextField_name.setEditable(false);
                flag = 1; 
            }
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null, "Connection Error");
        }
        
    }//GEN-LAST:event_searchButtonActionPerformed

    private void bookButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bookButtonActionPerformed
        if (flag==1){ //indicates that the patient name entered is correct
            String patientName = jTextField_name.getText();
            String doctor = (String)jComboBox_doctor.getSelectedItem();
            String date = jTextField_date.getText();
            String time = (String) jComboBox_time.getSelectedItem();
            String payment = null;
            
            if (jCheckBox_cash.isSelected()){
                payment = "Cash Walk In Payment";
            } 
            else if (jCheckBox_card.isSelected()){
                payment = "Card Payment";
            }          
            try{
                Connection con = DriverManager.getConnection("jdbc:mysql://localhost/login_register", "root", "");
                Statement st = con.createStatement();
                st.executeUpdate("insert into patientbooking values('" + patientName + "','" + doctor + "','" + date + "','" + time + "','" + payment + "')");
                JOptionPane.showMessageDialog(null, "Your booking is successfully completed!");
                setVisible(false);
                new patientMenu().setVisible(true);
            }
            catch(Exception e){
                JOptionPane.showMessageDialog(this, e);
            }      
        }
        else
            JOptionPane.showMessageDialog(null, "Please enter the patient name.");
    }//GEN-LAST:event_bookButtonActionPerformed

    private void jCheckBox_cashMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jCheckBox_cashMouseClicked
        lblFee.setVisible(true);
        jTextField_fee.setVisible(true);
        lblStatus.setVisible(true);
        jTextField_status.setVisible(true);
    }//GEN-LAST:event_jCheckBox_cashMouseClicked

    private void jCheckBox_cardMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jCheckBox_cardMouseClicked
       lblFee.setVisible(true);
       jTextField_fee.setVisible(true);
       lblStatus.setVisible(true);
       jTextField_status.setVisible(true);
    }//GEN-LAST:event_jCheckBox_cardMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(booking.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(booking.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(booking.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(booking.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new booking().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bookButton;
    private javax.swing.JButton cancelButton;
    private javax.swing.JLabel dontExist;
    private javax.swing.JCheckBox jCheckBox_card;
    private javax.swing.JCheckBox jCheckBox_cash;
    private javax.swing.JComboBox<String> jComboBox_doctor;
    private javax.swing.JComboBox<String> jComboBox_time;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField jTextField_date;
    private javax.swing.JTextField jTextField_fee;
    private javax.swing.JTextField jTextField_name;
    private javax.swing.JTextField jTextField_status;
    private javax.swing.JLabel lblDate;
    private javax.swing.JLabel lblDoctor;
    private javax.swing.JLabel lblFee;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblPayment;
    private javax.swing.JLabel lblStatus;
    private javax.swing.JLabel lblTime;
    private javax.swing.ButtonGroup paymentOptions;
    private javax.swing.JButton searchButton;
    private javax.swing.JTable tableRecord;
    // End of variables declaration//GEN-END:variables
}
